/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Michael' at '11/1/18 11:19 PM' with Gradle 2.14.1
 *
 * @author Michael, @date 11/1/18 11:19 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
